// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoGen.SourceGenerator.Template
{
    using System.Linq;
    using System.Collections.Generic;
    using Microsoft.CodeAnalysis;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal partial class LiteLlmFunctionCallTemplate : LiteLlmFunctionCallTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\xFEFFX");
            this.Write("//----------------------\r\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n// </auto-generated>\r\n//----------------------\r\nusing Azure.AI.OpenAI;\r\nusing System.Text.Json;\r\nusing System.Text.Json.Serialization;\r\nusing System.Threading.Tasks;\r\nusing System;\r\nusing AutoGen.Core;\r\nusing AutoGen.OpenAI.Extension;\r\n\r\n");
            
            #line 18 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (!String.IsNullOrEmpty(NameSpace)) {
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 19 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NameSpace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 21 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("    public partial class ");
            
            #line 22 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 24 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
foreach (var functionContract in FunctionContracts) {
            
            #line default
            #line hidden
            this.Write("\r\n        private class ");
            
            #line 26 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.GetFunctionSchemaClassName()));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n");
            
            #line 28 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
foreach (var parameter in functionContract.Parameters) {
            
            #line default
            #line hidden
            
            #line 29 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (parameter.IsOptional) {
            
            #line default
            #line hidden
            this.Write("            [JsonPropertyName(@\"");
            
            #line 30 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\t\t\tpublic ");
            
            #line 31 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 31 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(" {get; set;} = ");
            
            #line 31 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.DefaultValue));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 32 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
} else {
            
            #line default
            #line hidden
            this.Write("            [JsonPropertyName(@\"");
            
            #line 33 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\t\t\tpublic ");
            
            #line 34 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 34 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(" {get; set;}\r\n");
            
            #line 35 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 36 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public ");
            
            #line 39 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.ReturnType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 39 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.GetFunctionWrapperName()));
            
            #line default
            #line hidden
            this.Write("(string[] arguments)\r\n        {\r\n            var schema = JsonSerializer.Deserialize<");
            
            #line 41 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.GetFunctionSchemaClassName()));
            
            #line default
            #line hidden
            this.Write(">(\r\n                arguments, \r\n                new JsonSerializerOptions\r\n                {\r\n                    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,\r\n                });\r\n");
            
            #line 47 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
 var argumentLists = string.Join(", ", functionContract.Parameters.Select(p => $"schema.{p.Name}")); 
            
            #line default
            #line hidden
            this.Write("\r\n            return ");
            
            #line 49 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 49 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(argumentLists));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        public FunctionContract ");
            
            #line 52 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.GetFunctionContractName()));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get => new FunctionContract\r\n            {\r\n");
            
            #line 56 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (functionContract.Namespace != null) {
            
            #line default
            #line hidden
            this.Write("                Namespace = @\"");
            
            #line 57 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.Namespace));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 58 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 59 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (functionContract.ClassName != null) {
            
            #line default
            #line hidden
            this.Write("                ClassName = @\"");
            
            #line 60 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.ClassName));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 61 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 62 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (functionContract.Name != null) {
            
            #line default
            #line hidden
            this.Write("                Name = @\"");
            
            #line 63 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 64 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 65 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (functionContract.Description != null) {
            
            #line default
            #line hidden
            this.Write("                Description = @\"");
            
            #line 66 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.Description));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 67 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 68 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (functionContract.ReturnType != null) {
            
            #line default
            #line hidden
            this.Write("                ReturnType = typeof(");
            
            #line 69 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.ReturnType));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 70 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 71 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (functionContract.ReturnDescription != null) {
            
            #line default
            #line hidden
            this.Write("                ReturnDescription = @\"");
            
            #line 72 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.ReturnDescription));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 73 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 74 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (functionContract.Parameters != null) {
            
            #line default
            #line hidden
            this.Write("                Parameters = new []\r\n                {\r\n");
            
            #line 77 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
foreach (var parameter in functionContract.Parameters) {
            
            #line default
            #line hidden
            this.Write("                    new FunctionParameterContract\r\n                    {\r\n");
            
            #line 80 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (parameter.Name != null) {
            
            #line default
            #line hidden
            this.Write("                        Name = @\"");
            
            #line 81 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 82 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 83 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (parameter.Description != null) {
            
            #line default
            #line hidden
            this.Write("                        Description = @\"");
            
            #line 84 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Description));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 85 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 86 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (parameter.Type != null) {
            
            #line default
            #line hidden
            this.Write("                        ParameterType = typeof(");
            
            #line 87 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 88 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                        IsRequired = ");
            
            #line 89 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.IsOptional ? "false" : "true"));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 90 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (parameter.DefaultValue != null) {
            
            #line default
            #line hidden
            this.Write("                        DefaultValue = ");
            
            #line 91 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.DefaultValue));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 92 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                    },\r\n");
            
            #line 94 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("                },\r\n");
            
            #line 96 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("            };\r\n        }\r\n\r\n        public FunctionDefinition ");
            
            #line 100 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.GetFunctionDefinitionName()));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get => this.");
            
            #line 102 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(functionContract.GetFunctionContractName()));
            
            #line default
            #line hidden
            this.Write(".ToOpenAIFunctionDefinition();\r\n        }\r\n");
            
            #line 104 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 106 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
if (!String.IsNullOrEmpty(NameSpace)) {
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 108 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 110 "C:\code\autogen\dotnet\src\AutoGen.SourceGenerator\Template\LiteLlmFunctionCallTemplate.tt"

public string NameSpace {get; set;}
public string ClassName {get; set;}
public IEnumerable<FunctionContract> FunctionContracts {get; set;}
public bool IsStatic {get; set;} = false;

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal class LiteLlmFunctionCallTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
